# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20170814_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
