# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_time',
            field=models.DateTimeField(null=True),
        ),
    ]
