# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170715_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(),
        ),
    ]
