# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 21:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170716_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.models.validate_is_blank, django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
