# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
