# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170716_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
