# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 23, 21, 1, 696437)),
            preserve_default=False,
        ),
    ]
